# Generated by Django 4.1.9 on 2023-06-20 09:44

import core.models
from django.db import migrations, models
import django.db.models.deletion
import timezone_field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11, validators=[core.models.validate_phone_number])),
                ('operator_code', models.CharField(max_length=6)),
                ('tag', models.CharField(max_length=255)),
                ('timezone', timezone_field.fields.TimeZoneField(default='Europe/Moscow')),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('message_text', models.TextField()),
                ('client_filter_operator_code', models.CharField(max_length=10)),
                ('client_filter_tag', models.CharField(max_length=255)),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField()),
                ('delivery_status', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mailing')),
            ],
        ),
    ]
